
#设置Tomcat访问端口号
server:
    port: 8080

#设置数据库连接
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        password: root
        username: root

#设置mapper映射
mybatis:
    mapper-locations: classpath:mapper/*.xml